import intf_libs = libpmp%lib{pmp}

import intf_libs += glew%lib{glew}
import intf_libs += libimgui-platform-glfw%lib{imgui-platform-glfw}
import intf_libs += libimgui-render-opengl3%lib{imgui-render-opengl3}

import impl_libs = stb_image%lib{stb_image}
import impl_libs += stb_image_write%lib{stb_image_write}

lib{pmp-vis}: libul{pmp-vis}: ../{hxx cxx}{*} {hxx cxx}{**} $impl_libs $intf_libs

# Automatic DLL Symbol Exportation on Windows
#
libs{pmp-vis}: def{pmp-vis}: include = ($cxx.target.system == 'win32-msvc')
def{pmp-vis}: libul{pmp-vis}
if ($cxx.target.system == 'mingw32')
  cxx.loptions += -Wl,--export-all-symbols

# Build and Export Options
#
cxx.poptions =+ "-I$src_root"
lib{pmp-vis}:
{
  cxx.export.poptions = "-I$src_root"
  cxx.export.libs = $intf_libs
}

if ($cxx.target.class == 'windows')
  cxx.poptions += -DNOMINMAX -D_CRT_SECURE_NO_WARNINGS

switch $cxx.id
{
  case 'msvc'
    cxx.coptions += /wd4267 /wd4244 /wd4305

  case 'gcc' | 'clang' | 'clang-apple'
    cxx.coptions += -Wno-deprecated-copy -Wno-int-in-bool-context
}

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{pmp-vis}: bin.lib.version = "-$version.project_id"
else
  lib{pmp-vis}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libpmp/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
hxx{*}:
{
  install         = include/pmp/
  install.subdirs = true
}
