import intf_libs = Eigen%lib{Eigen}
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{pmp}: {hxx cxx}{**} $impl_libs $intf_libs

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

obja{*}: cxx.poptions += -DLIBPMP_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBPMP_SHARED_BUILD

# Export options.
#
lib{pmp}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{pmp}: cxx.export.poptions += -DLIBPMP_STATIC
libs{pmp}: cxx.export.poptions += -DLIBPMP_SHARED

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{pmp}: bin.lib.version = "-$version.project_id"
else
  lib{pmp}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libpmp/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
hxx{*}:
{
  install         = include/pmp/
  install.subdirs = true
}
